sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - stable
matrix:
  allow_failures:
    - name: "Clippy: stable"
  include:
    - rust: stable
      name: "Format: stable"
      script:
        - rustup component add rustfmt
        - cargo fmt -- --check
    - rust: stable
      name: "Clippy: stable"
      script:
        - rustup component add clippy
        - cargo clippy
script:
  - cargo build
  - cargo doc
  - cargo test
  - cargo test --features genmesh
